imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:   stream
            path:   %kernel.logs_dir%/%kernel.environment%.log
            level:  debug
        console:
            type:   console
            bubble: false
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

assetic:
    use_controller: true

#swiftmailer:
#    delivery_address: me@example.com

web_profiler_extra:
    routing:
        enabled:        false
        display_in_wdt: false
    container:
        enabled:        true
        display_in_wdt: false
    assetic:
        enabled:        false
        display_in_wdt: false
    twig:
        enabled:        false
        display_in_wdt: false

sputnik_pubsub:
    live_hub: false

raul_fraile_ladybug:
    object_max_nesting_level: 5

jns_xhprof:
    location_web:    http://xhprof.localhost
    enabled:         true
