parameters:
    caxy_elasticsearch.setup:
        production: [ atom ]

    caxy_elasticsearch.index.params:
        production:
            settings:
                analysis:
                    analyzer:
                        tag_analyzer:
                            filter:
                                - lowercase
                                - trim
                                - unique
                            tokenizer: keyword

    caxy_elasticsearch.mapping.params:
        atom:
            properties:
                _attachments:
                    properties:
                        original:
                            properties:
                                content_type:
                                    type: string
                                digest:
                                    type: string
                                length:
                                    type: long
                                revpos:
                                    type: long
                _rev:
                    type: string
                authors:
                    type: object
                    properties:
                        email:
                            type: string
                        name:
                            type: string
                            index: not_analyzed
                        uri:
                            type: string
                categories:
                    type: object
                    properties:
                        term:
                            type: string
                            analyzer: tag_analyzer
                        scheme:
                            type: string
                        label:
                            type: string
                content:
                    type: object
                    properties:
                        content:
                            type: string
                        src:
                            type: string
                        type:
                            type: string
                doctrine_metadata:
                    type: object
                    enabled: false
                id:
                    type: string
                links:
                    properties:
                        href:
                            type: string
                        type:
                            type: string
                        rel:
                            type: string
                        title:
                            type: string
                published:
                    type: date
                    format: "yyyy-MM-dd HH:mm:ss.SSSSSS"
                    ignore_malformed: true
                source:
                    properties:
                        authors:
                            type: object
                            properties:
                                email:
                                    type: string
                                name:
                                    type: string
                                    index: not_analyzed
                                uri:
                                    type: string
                        categories:
                            type: object
                            properties:
                                term:
                                    type: string
                                    analyzer: tag_analyzer
                                scheme:
                                    type: string
                                label:
                                    type: string
                        id:
                            type: string
                        links:
                            type: object
                            properties:
                                href:
                                    type: string
                                type:
                                    type: string
                                rel:
                                    type: string
                                title:
                                    type: string
                        title:
                            type: object
                            properties:
                                text:
                                    type: string
                                    index: not_analyzed
                                type:
                                    type: string
                        type:
                            type: string
                        updated:
                            type: date
                            format: "yyyy-MM-dd HH:mm:ss.SSSSSS"
                            ignore_malformed: true
                summary:
                    type: object
                    properties:
                        text:
                            type: string
                        type:
                            type: string
                title:
                    type: object
                    properties:
                        text:
                            type: string
                        type:
                            type: string
                type:
                    type: string
                updated:
                    type: date
                    format: "yyyy-MM-dd HH:mm:ss.SSSSSS"
                    ignore_malformed: true
