bangpound_castle:
    resource: "@BangpoundCastleBundle/Resources/config/routing.yml"
    prefix:   /

site_home:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template: 'site_home.html.twig'

_monitor:
    resource: "@LiipMonitorBundle/Resources/config/routing.xml"
    prefix: /monitor/health

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

_fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix:   /admin

sputnik_pubsub_hub:
    resource: "@SputnikPubsubBundle/Resources/config/routing/hub.xml"
    prefix:   /hub

sputnik_pubsub_callback:
    resource: "@SputnikPubsubBundle/Resources/config/routing/callback.xml"
    prefix:   /push

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
